INSERT INTO customer (id,balance) VALUES (1,1000) ON DUPLICATE KEY UPDATE id=1;
INSERT INTO customer (id,balance) VALUES (2,5000) ON DUPLICATE KEY UPDATE id=2;
INSERT INTO customer (id,balance) VALUES (3,10000) ON DUPLICATE KEY UPDATE id=3;